### ISSUE TITLE
json rpc issue - fail more gracefully?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#158]
Was looking at a miiner which had following errors on diag. I am pretty sure from looking at it that essentially there was a problem with the helium-miner container which was causing it to hang (a purge solved it). However, this was not immediately obvious due to the below errors, meaning the diag page just showed "diag not run, please wait a few minutes".

When failing in this way - perhaps it would be better to show a different error message that clarifies what is actually happening?

```
 diagnostics  Job "get_app.<locals>.run_diagnostics_task (trigger: cron[minute='*/5'], next run at: 2021-09-24 23:05:00 UTC)" raised an exception
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
 diagnostics      conn = connection.create_connection(
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
 diagnostics      raise err
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
 diagnostics      sock.connect(sa)
 diagnostics  ConnectionRefusedError: [Errno 111] Connection refused
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
 diagnostics      httplib_response = self._make_request(
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
 diagnostics      conn.request(method, url, **httplib_request_kw)
 diagnostics    File "/usr/lib/python3.8/http/client.py", line 1252, in request
 diagnostics      self._send_request(method, url, body, headers, encode_chunked)
 diagnostics    File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
 diagnostics      self.endheaders(body, encode_chunked=encode_chunked)
 diagnostics    File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
 diagnostics      self._send_output(message_body, encode_chunked=encode_chunked)
 diagnostics    File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
 diagnostics      self.send(msg)
 diagnostics    File "/usr/lib/python3.8/http/client.py", line 947, in send
 diagnostics      self.connect()
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
 diagnostics      conn = self._new_conn()
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
 diagnostics      raise NewConnectionError(
 diagnostics  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xf5c37b50>: Failed to establish a new connection: [Errno 111] Connection refused
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
 diagnostics      resp = conn.urlopen(
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
 diagnostics      retries = retries.increment(
 diagnostics    File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
 diagnostics      raise MaxRetryError(_pool, url, error or ResponseError(cause))
 diagnostics  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='helium-miner', port=4467): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xf5c37b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/usr/lib/python3.8/site-packages/hw_diag-1.0-py3.8.egg/hw_diag/utilities/miner.py", line 36, in fetch_miner_data
 diagnostics      public_key = client.get_peer_addr().get('peer_addr').split('/')[2]
 diagnostics    File "/usr/lib/python3.8/site-packages/hm_pyhelper/miner_json_rpc/client.py", line 23, in get_peer_addr
 diagnostics      return self.__fetch_data('peer_addr')
 diagnostics    File "/usr/lib/python3.8/site-packages/hm_pyhelper/miner_json_rpc/client.py", line 10, in __fetch_data
 diagnostics      response = request(self.url, method, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/jsonrpcclient/__init__.py", line 8, in request
 diagnostics      return HTTPClient(endpoint).request(*args, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/apply_defaults/decorators.py", line 13, in wrapper
 diagnostics      return function(self, *args, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/jsonrpcclient/client.py", line 229, in request
 diagnostics      return self.send(
 diagnostics    File "/usr/lib/python3.8/site-packages/apply_defaults/decorators.py", line 13, in wrapper
 diagnostics      return function(self, *args, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/jsonrpcclient/client.py", line 167, in send
 diagnostics      response = self.send_message(
 diagnostics    File "/usr/lib/python3.8/site-packages/jsonrpcclient/clients/http_client.py", line 63, in send_message
 diagnostics      response = self.session.post(self.endpoint, data=request.encode(), **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
 diagnostics      return self.request('POST', url, data=data, json=json, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
 diagnostics      resp = self.send(prep, **send_kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
 diagnostics      r = adapter.send(request, **kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
 diagnostics      raise ConnectionError(e, request=request)
 diagnostics  requests.exceptions.ConnectionError: HTTPConnectionPool(host='helium-miner', port=4467): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xf5c37b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/usr/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
 diagnostics      retval = job.func(*job.args, **job.kwargs)
 diagnostics    File "/usr/lib/python3.8/site-packages/hw_diag-1.0-py3.8.egg/hw_diag/app.py", line 34, in run_diagnostics_task
 diagnostics      perform_hw_diagnostics()
 diagnostics    File "/usr/lib/python3.8/site-packages/hw_diag-1.0-py3.8.egg/hw_diag/tasks.py", line 37, in perform_hw_diagnostics
 diagnostics      diagnostics = fetch_miner_data(diagnostics)
 diagnostics    File "/usr/lib/python3.8/site-packages/hw_diag-1.0-py3.8.egg/hw_diag/utilities/miner.py", line 40, in fetch_miner_data
 diagnostics      raise Exception("Unable to fetch keys from miner container "
 diagnostics  Exception: Unable to fetch keys from miner container via JSON RPC API. Exception: HTTPConnectionPool(host='helium-miner', port=4467): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xf5c37b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
 diagnostics  [2021-09-24 23:00:01 +0000] [1] [INFO] Shutting down: Master
```

**Comment by robputt** [comment]
JSON RPC is going in the bin in favour of gRPC API with gateway-rs transition. Closing.
