### ISSUE TITLE
Fix onboarding_address error

### ISSUE THREAD

**Issue by kashifpk** [NebraLtd/hm-diag#257]
In manufacturing with latest firmware the response we get from `/initFile.txt` gets decoded to

```python
{
    'eth_mac': 'F0:4C:D5:58:F2:D9', 
    'frequency': '915', 
    'hotspot_id': 'a1166464076f44cc752e463d848b4350', 
    'onboarding_address': 'gateway_mfr exited with a non-zero status', 
    'serial_number': '0000000029a371bc', 
    'variant': 'NEBHNT-OUT1', 
    'wifi_mac': '00:52:11:00:0F:07'
}
```

Here ` 'onboarding_address': 'gateway_mfr exited with a non-zero status',` causes the miner registration to fail in the dashboard.

**Comment by vpetersson** [comment]
This is up for grabs for anyone. We need to square this one out asap.

**Comment by kashifpk** [comment]
I'll check if it's fixed as @marvinmarnold had fix for this in PR for quite a few days. So will just double check and update here.

**Comment by kashifpk** [comment]
Update: If errors is empty then send request to on boarding server. Otherwise treat the values for those keys as error messages.

**Comment by kashifpk** [comment]
Remove this device after fix is applied.

https://dashboard.nebra.com/admin/device/devices/0000000021bc1190/change/?_changelist_filters=q%3Dgateway_mfr

**Comment by kashifpk** [comment]
Confirmed at testnet that the `/initFile.txt` payload does not contain the null character. @vpetersson I guess the firmeware we sent to manufacturing did not have this change or may be they were still using an older firmware. I'm going to add quick code into HPT to also query the `/version` endpoint and display it's output so it's easier for us to determine such things instead of relying on what manufacturing tells us.

### Decoded initFile.txt payload from one of the devices on testnet.

{
    'diagnostics_passed': True,     
    'errors': [],
    'serial_number': '0000000016c18b51',
    'ECC': True,
    'E0': '00:BD:27:78:0C:CB',
    'eth_mac_address': '00:BD:27:78:0C:CB',
    'W0': '66:8D:7C:D5:B0:FD',
    'wifi_mac_address': '66:8D:7C:D5:B0:FD',
    'BN': 'little-tree',
    'BALENA_DEVICE_NAME_AT_INIT': 'little-tree',
    'ID': 'b93d99192808f74a246beb0dd72aefd0',
    'BALENA_DEVICE_UUID': 'b93d99192808f74a246beb0dd72aefd0',
    'BA': 'HELIUM-TESTNET',
    'BALENA_APP_NAME': 'HELIUM-TESTNET',
    'FR': '868',
    'FREQ': '868',
    'FW': '2021.11.30.1',
    'FIRMWARE_VERSION': '2021.11.30.1',
    'VA': 'NEBHNT-IN1',
    'VARIANT': 'NEBHNT-IN1',
    'BT': True,
    'LTE': False,
    'LOR': True,
    'lora': True,
    'OK': '112YE7uBMX2qwgDqT3bSokzKcnR5mqheWMUd1h887rc8WFHtHsxQ',
    'onboarding_key': '112YE7uBMX2qwgDqT3bSokzKcnR5mqheWMUd1h887rc8WFHtHsxQ',
    'PK': '112YE7uBMX2qwgDqT3bSokzKcnR5mqheWMUd1h887rc8WFHtHsxQ',
    'public_key': '112YE7uBMX2qwgDqT3bSokzKcnR5mqheWMUd1h887rc8WFHtHsxQ',
    'PF': True,
    'legacy_pass_fail': True
}

Since the part of not sending on-boarding requests for devices with errors is handled in https://github.com/NebraLtd/Hotspot-Production-Tool/issues/64 this issue can be closed once we send them new firmware version based on the current master.

**Comment by kashifpk** [comment]
Looks like @marvinmarnold's serial number fix was merged with master on Nov 27

![image](https://user-images.githubusercontent.com/198638/144363443-0f57d833-fa42-49fb-a70a-b779dbd41b48.png)

So may be it didn't get into the last firmware we sent them? But this is strange because building the firmware we confirmed that master and production were synced. So might be the case of them plugging in miner with older firmware onto the hotspot production tool @vpetersson.

**Comment by kashifpk** [comment]
This concludes that t he previous firmware should have this fix. So we don't really need to send them new firmware? I'll just update HPT to query `/version` and see if they are actually using correct firmware.

**Comment by salmanfarisvp** [comment]
sharing balena log dump 

```
02.12.21 17:30:00 (+0530)  helium-miner  Crash dump is being written to: erl_crash.dump...done
02.12.21 17:30:02 (+0530) Service exited 'helium-miner sha256:fb885fa0019fe1ff6dcbdddb370ead7b104caf4e67ebef1be4ad68b9c0b0ab1f'
02.12.21 17:30:02 (+0530)  packet-forwarder  2021-12-02 12:00:02,432 - [DEBUG] - hm_pyhelper.miner_param - (miner_param.py).retry_get_region -- /opt/pktfwd-dependencies/hm_pyhelper/miner_param.py:(199) - No region override set (value = False), will retrieve from miner.
02.12.21 17:30:02 (+0530)  packet-forwarder  2021-12-02 12:00:02,433 - [WARNING] - hm_pyhelper.miner_param - (api.py).__retry_internal -- /opt/pktfwd-dependencies/retry/api.py:(40) - [Errno 2] No such file or directory: '/var/pktfwd/region', retrying in 60 seconds...
02.12.21 17:30:04 (+0530)  helium-miner  Connecting to helium-assets.nebra.com (104.18.19.22:443)
02.12.21 17:30:04 (+0530)  helium-miner  saving to '/opt/miner/releases/2021.11.30.1/sys.config'
sys.config           100% |********************************|  6055  0:00:00 ETA
02.12.21 17:30:04 (+0530)  helium-miner  '/opt/miner/releases/2021.11.30.1/sys.config' saved
02.12.21 17:30:04 (+0530)  diagnostics  DEBUG:flask_caching.backends.simplecache:get key 'view//initFile.txt' -> miss (expired)
02.12.21 17:30:05 (+0530)  diagnostics  2021-12-02 12:00:05,010 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(41) - gateway_mfr response stdout: b'{\n  "result": "fail",\n  "tests": [\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "serial"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(data)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(config)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "slot_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "key_config(0..=15, ecc)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "miner_key(0)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "sign(0)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "ecdh(0)"\n    }\n  ]\n}\n'
02.12.21 17:30:05 (+0530)  diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stdout: b'{\n  "result": "fail",\n  "tests": [\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "serial"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(data)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(config)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "slot_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "key_config(0..=15, ecc)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "miner_key(0)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "sign(0)"\n    },\n    {\n      "output": "decode error\\n\\nCaused by:\\n    not a compact key",\n      "result": "fail",\n      "test": "ecdh(0)"\n    }\n  ]\n}\n'
02.12.21 17:30:05 (+0530)  diagnostics  2021-12-02 12:00:05,012 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(43) - gateway_mfr response stderr: b''
02.12.21 17:30:05 (+0530)  diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stderr: b''
02.12.21 17:30:05 (+0530)  diagnostics  setting BT to True
02.12.21 17:30:05 (+0530)  diagnostics  2021-12-02 12:00:05,189 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(47) - gateway_mfr exited with a non-zero status
02.12.21 17:30:05 (+0530)  diagnostics  Traceback (most recent call last):
02.12.21 17:30:05 (+0530)  diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 36, in run_gateway_mfr
02.12.21 17:30:05 (+0530)  diagnostics      run_gateway_mfr_result = subprocess.run(
02.12.21 17:30:05 (+0530)  diagnostics    File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
02.12.21 17:30:05 (+0530)  diagnostics      raise CalledProcessError(retcode, process.args,
02.12.21 17:30:05 (+0530)  diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr', 'key', '0']' returned non-zero exit status 1.
02.12.21 17:30:05 (+0530)  diagnostics  ERROR:hm_pyhelper.miner_param:gateway_mfr exited with a non-zero status
02.12.21 17:30:05 (+0530)  diagnostics  Traceback (most recent call last):
02.12.21 17:30:05 (+0530)  diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 36, in run_gateway_mfr
02.12.21 17:30:05 (+0530)  diagnostics      run_gateway_mfr_result = subprocess.run(
02.12.21 17:30:05 (+0530)  diagnostics    File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
02.12.21 17:30:05 (+0530)  diagnostics      raise CalledProcessError(retcode, process.args,
02.12.21 17:30:05 (+0530)  diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr', 'key', '0']' returned non-zero exit status 1.
02.12.21 17:30:05 (+0530)  diagnostics  2021-12-02 12:00:05,270 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(47) - gateway_mfr exited with a non-zero status
02.12.21 17:30:05 (+0530)  diagnostics  Traceback (most recent call last):
02.12.21 17:30:05 (+0530)  diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 36, in run_gateway_mfr
02.12.21 17:30:05 (+0530)  diagnostics      run_gateway_mfr_result = subprocess.run(
02.12.21 17:30:05 (+0530)  diagnostics    File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
02.12.21 17:30:05 (+0530)  diagnostics      raise CalledProcessError(retcode, process.args,
02.12.21 17:30:05 (+0530)  diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr', 'key', '0']' returned non-zero exit status 1.
02.12.21 17:30:05 (+0530)  diagnostics  ERROR:hm_pyhelper.miner_param:gateway_mfr exited with a non-zero status
02.12.21 17:30:05 (+0530)  diagnostics  Traceback (most recent call last):
02.12.21 17:30:05 (+0530)  diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 36, in run_gateway_mfr
02.12.21 17:30:05 (+0530)  diagnostics      run_gateway_mfr_result = subprocess.run(
02.12.21 17:30:05 (+0530)  diagnostics    File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
02.12.21 17:30:05 (+0530)  diagnostics      raise CalledProcessError(retcode, process.args,
02.12.21 17:30:05 (+0530)  diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr', 'key', '0']' returned non-zero exit status 1.
02.12.21 17:30:05 (+0530)  diagnostics  2021-12-02 12:00:05,272 - [DEBUG] - hw_diag.views.diagnostics - (diagnostics.py).get_initialisation_file -- /opt/python-dependencies/hw_diag/views/diagnostics.py:(92) - Full diagnostics report is: {'diagnostics_passed': False, 'errors': ['ECC', 'LOR', 'OK', 'PK', 'PF'], 'serial_number': '00000000b2615f58', 'ECC': 'gateway_mfr test finished with error, {"result": "fail", "tests": [{"output": "ok", "result": "pass", "test": "serial"}, {"output": "ok", "result": "pass", "test": "zone_locked(data)"}, {"output": "ok", "result": "pass", "test": "zone_locked(config)"}, {"output": "ok", "result": "pass", "test": "slot_config(0..=15, ecc)"}, {"output": "ok", "result": "pass", "test": "key_config(0..=15, ecc)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "miner_key(0)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "sign(0)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "ecdh(0)"}]}', 'E0': 'F0:4C:D5:AC:4E:93', 'eth_mac_address': 'F0:4C:D5:AC:4E:93', 'W0': 'BC:EC:23:80:A9:FF', 'wifi_mac_address': 'BC:EC:23:80:A9:FF', 'BN': 'floral-firefly', 'BALENA_DEVICE_NAME_AT_INIT': 'floral-firefly', 'ID': '9869a5ba7a0880d39e95862afe42e809', 'BALENA_DEVICE_UUID': '9869a5ba7a0880d39e95862afe42e809', 'BA': 'HELIUM-INDOOR-915', 'BALENA_APP_NAME': 'HELIUM-INDOOR-915', 'FR': '915', 'FREQ': '915', 'FW': '2021.11.30.1', 'FIRMWARE_VERSION': '2021.11.30.1', 'VA': 'NEBHNT-IN1', 'VARIANT': 'NEBHNT-IN1', 'BT': True, 'LTE': False, 'LOR': False, 'lora': False, 'OK': 'gateway_mfr exited with a non-zero status', 'onboarding_key': 'gateway_mfr exited with a non-zero status', 'PK': 'gateway_mfr exited with a non-zero status', 'public_key': 'gateway_mfr exited with a non-zero status', 'PF': False, 'legacy_pass_fail': False}
02.12.21 17:30:05 (+0530)  diagnostics  DEBUG:hw_diag.views.diagnostics:Full diagnostics report is: {'diagnostics_passed': False, 'errors': ['ECC', 'LOR', 'OK', 'PK', 'PF'], 'serial_number': '00000000b2615f58', 'ECC': 'gateway_mfr test finished with error, {"result": "fail", "tests": [{"output": "ok", "result": "pass", "test": "serial"}, {"output": "ok", "result": "pass", "test": "zone_locked(data)"}, {"output": "ok", "result": "pass", "test": "zone_locked(config)"}, {"output": "ok", "result": "pass", "test": "slot_config(0..=15, ecc)"}, {"output": "ok", "result": "pass", "test": "key_config(0..=15, ecc)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "miner_key(0)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "sign(0)"}, {"output": "decode error\\n\\nCaused by:\\n    not a compact key", "result": "fail", "test": "ecdh(0)"}]}', 'E0': 'F0:4C:D5:AC:4E:93', 'eth_mac_address': 'F0:4C:D5:AC:4E:93', 'W0': 'BC:EC:23:80:A9:FF', 'wifi_mac_address': 'BC:EC:23:80:A9:FF', 'BN': 'floral-firefly', 'BALENA_DEVICE_NAME_AT_INIT': 'floral-firefly', 'ID': '9869a5ba7a0880d39e95862afe42e809', 'BALENA_DEVICE_UUID': '9869a5ba7a0880d39e95862afe42e809', 'BA': 'HELIUM-INDOOR-915', 'BALENA_APP_NAME': 'HELIUM-INDOOR-915', 'FR': '915', 'FREQ': '915', 'FW': '2021.11.30.1', 'FIRMWARE_VERSION': '2021.11.30.1', 'VA': 'NEBHNT-IN1', 'VARIANT': 'NEBHNT-IN1', 'BT': True, 'LTE': False, 'LOR': False, 'lora': False, 'OK': 'gateway_mfr exited with a non-zero status', 'onboarding_key': 'gateway_mfr exited with a non-zero status', 'PK': 'gateway_mfr exited with a non-zero status', 'public_key': 'gateway_mfr exited with a non-zero status', 'PF': False, 'legacy_pass_fail': False}
02.12.21 17:30:05 (+0530)  diagnostics  DEBUG:flask_caching.backends.simplecache:set key 'view//initFile.txt'
02.12.21 17:30:05 (+0530)  helium-miner  method return time=1638446405.291337 sender=org.freedesktop.DBus -> destination=:1.81 serial=3 reply_serial=2
02.12.21 17:30:05 (+0530)  helium-miner     array [
02.12.21 17:30:05 (+0530)  helium-miner        string "org.freedesktop.DBus"
02.12.21 17:30:05 (+0530)  helium-miner        string ":1.81"
02.12.21 17:30:05 (+0530)  helium-miner     ]
02.12.21 17:30:05 (+0530)  helium-miner  DBus is now accepting connections
02.12.21 17:30:05 (+0530) Restarting service 'helium-miner sha256:fb885fa0019fe1ff6dcbdddb370ead7b104caf4e67ebef1be4ad68b9c0b0ab1f'
02.12.21 17:30:05 (+0530)  helium-miner  Exec: /opt/miner/erts-11.2.2.6/bin/erlexec -noinput +Bd -boot /opt/miner/releases/2021.11.30.1/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/miner/lib -config /opt/miner/releases/2021.11.30.1/sys.config -args_file /opt/miner/releases/2021.11.30.1/vm.args -- foreground
02.12.21 17:30:05 (+0530)  helium-miner  Root: /opt/miner
02.12.21 17:30:05 (+0530)  helium-miner  /opt/miner
02.12.21 17:30:08 (+0530)  upnp  File Not Detected, Sleeping
02.12.21 17:30:11 (+0530)  helium-miner  {"Kernel pid terminated",application_controller,"{application_start_failure,miner,{{{badmatch,{error,empty_slot}},[{miner_keys,keys,1,[{file,\"miner_keys.erl\"},{line,87}]},{miner_sup,init,1,[{file,\"miner_sup.erl\"},{line,67}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,301}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]},{miner_app,start,[normal,[]]}}}"}
02.12.21 17:30:11 (+0530)  helium-miner  Kernel pid terminated (application_controller) ({application_start_failure,miner,{{{badmatch,{error,empty_slot}},[{miner_keys,keys,1,[{file,"miner_keys.erl"},{line,87}]},{miner_sup,init,1,[{file,"mine
```

**/initFile.txt** log 

```
{
  "diagnostics_passed": false,
  "errors": [
    "ECC",
    "LOR",
    "OK",
    "PK",
    "PF"
  ],
  "serial_number": "00000000b2615f58",
  "ECC": "gateway_mfr test finished with error, {\"result\": \"fail\", \"tests\": [{\"output\": \"ok\", \"result\": \"pass\", \"test\": \"serial\"}, {\"output\": \"ok\", \"result\": \"pass\", \"test\": \"zone_locked(data)\"}, {\"output\": \"ok\", \"result\": \"pass\", \"test\": \"zone_locked(config)\"}, {\"output\": \"ok\", \"result\": \"pass\", \"test\": \"slot_config(0..=15, ecc)\"}, {\"output\": \"ok\", \"result\": \"pass\", \"test\": \"key_config(0..=15, ecc)\"}, {\"output\": \"decode error\\n\\nCaused by:\\n    not a compact key\", \"result\": \"fail\", \"test\": \"miner_key(0)\"}, {\"output\": \"decode error\\n\\nCaused by:\\n    not a compact key\", \"result\": \"fail\", \"test\": \"sign(0)\"}, {\"output\": \"decode error\\n\\nCaused by:\\n    not a compact key\", \"result\": \"fail\", \"test\": \"ecdh(0)\"}]}",
  "E0": "F0:4C:D5:AC:4E:93",
  "eth_mac_address": "F0:4C:D5:AC:4E:93",
  "W0": "BC:EC:23:80:A9:FF",
  "wifi_mac_address": "BC:EC:23:80:A9:FF",
  "BN": "floral-firefly",
  "BALENA_DEVICE_NAME_AT_INIT": "{manually removed}",
  "ID": "9869a5ba7a0880d39e95862afe42e809",
  "BALENA_DEVICE_UUID": "9869a5ba7a0880d39e95862afe42e809",
  "BA": "HELIUM-INDOOR-915",
  "BALENA_APP_NAME": "HELIUM-INDOOR-915",
  "FR": "915",
  "FREQ": "915",
  "FW": "2021.11.30.1",
  "FIRMWARE_VERSION": "2021.11.30.1",
  "VA": "NEBHNT-IN1",
  "VARIANT": "NEBHNT-IN1",
  "BT": true,
  "LTE": false,
  "LOR": false,
  "lora": false,
  "OK": "gateway_mfr exited with a non-zero status",
  "onboarding_key": "gateway_mfr exited with a non-zero status",
  "PK": "gateway_mfr exited with a non-zero status",
  "public_key": "gateway_mfr exited with a non-zero status",
  "PF": false,
  "legacy_pass_fail": false
}
```

![image](https://user-images.githubusercontent.com/11945360/144418743-1bb0f003-b012-4789-be41-e007d7567485.png)

**Comment by kashifpk** [comment]
yes this looks consistent with what we saw in manufacturing today. same
error. looks like current production is broken.

**Comment by kashifpk** [comment]
> sharing balena log dump , issue is related #239

@salmanfarisvp @vpetersson - This seems different from the error we're facing at manufacturing. Because so far it looks like that error is only manufacturing specific and does not effect devices on testnet and production. So may be something else is causing this.

**Comment by salmanfarisvp** [comment]
@kashifpk We receved the same error on a few more devices yesterday!

**Comment by kashifpk** [comment]
@salmanfarisvp - Can you share balena dashboard links for those devices? That might help in figuring out what's going on.

**Comment by salmanfarisvp** [comment]
Sure @kashifpk, affected device links shared as slack DM.

**Comment by marvinmarnold** [comment]
@kashifpk can you link related PRs and closed

**Comment by kashifpk** [comment]
@marvinmarnold - This error is different from the manufacturing error issue https://github.com/NebraLtd/hm-diag/issues/264. I accidentally thought it was that issue.

This can be tackled later as this is only happening on some devices in production.

**Comment by marvinmarnold** [comment]
@vpetersson this no longer appears to be an "unbreak now" FYI
