### ISSUE TITLE
500 error on HNT page

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#539]
Log output:

```
  diagnostics  ERROR:hw_diag.wsgi:Exception on /hnt [GET]
  diagnostics  Traceback (most recent call last):
  diagnostics    File "/opt/python-dependencies/flask/app.py", line 2525, in wsgi_app
  diagnostics      response = self.full_dispatch_request()
  diagnostics                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/flask/app.py", line 1822, in full_dispatch_request
  diagnostics      rv = self.handle_user_exception(e)
  diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/flask/app.py", line 1820, in full_dispatch_request
  diagnostics      rv = self.dispatch_request()
  diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/flask/app.py", line 1796, in dispatch_request
  diagnostics      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  diagnostics             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/hw_diag/utilities/auth.py", line 22, in wrapper
  diagnostics      return f(*args, **kwargs)
  diagnostics             ^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/hw_diag/views/diagnostics.py", line 92, in get_helium_info
  diagnostics      response = render_template(
  diagnostics                 ^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/flask/templating.py", line 147, in render_template
  diagnostics      return _render(app, template, context)
  diagnostics             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/flask/templating.py", line 130, in _render
  diagnostics      rv = template.render(context)
  diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/jinja2/environment.py", line 1301, in render
  diagnostics      self.environment.handle_exception()
  diagnostics    File "/opt/python-dependencies/jinja2/environment.py", line 936, in handle_exception
  diagnostics      raise rewrite_traceback_stack(source=source)
  diagnostics    File "/opt/python-dependencies/hw_diag/templates/helium_info.html", line 1, in top-level template code
  diagnostics      {% extends 'template_hyper.html' %}
  diagnostics      ^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/hw_diag/templates/template_hyper.html", line 150, in top-level template code
  diagnostics      {% block body %}{% endblock %}
  diagnostics      ^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/hw_diag/templates/helium_info.html", line 60, in block 'body'
  diagnostics      {% if not diagnostics.has_errors([DIAG_CONSTS.GATEWAY_REGION_KEY]) %}
  diagnostics      ^^^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics    File "/opt/python-dependencies/jinja2/environment.py", line 485, in getattr
  diagnostics      return getattr(obj, attribute)
  diagnostics             ^^^^^^^^^^^^^^^^^^^^^^^
  diagnostics  jinja2.exceptions.UndefinedError: 'DIAG_CONSTS' is undefined
```

**Comment by shawaj** [comment]
Still not working:
```
ERROR:hw_diag.wsgi:Exception on /hnt [GET]
Traceback (most recent call last):
  File "/opt/python-dependencies/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/hw_diag/utilities/auth.py", line 65, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/hw_diag/views/diagnostics.py", line 94, in get_helium_info
    region_error = diagnostics.has_errors([GATEWAY_REGION_KEY])
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'has_errors'
INFO:root:Running periodic hardware diagnostics
```
