### ISSUE TITLE
Backup dialog causes a "file not found" error

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#584]
Due to #582 the diagnostics is showing a 500 error after logging in due to a file not found error as shown below:

```
DEBUG:urllib3.connectionpool:https://icanhazip.com:443 "GET / HTTP/1.1" 200 12
2023-05-30 00:08:38,152 - [DEBUG] - hw_diag.utilities.backup.myst - (myst.py).identity_hash -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/myst.py:(28) - myst keystore files: ['/var/myst/keystore/UTC--2023-05-17T07-02-11.762878233Z--4e789ceca3f786a2ad8155144d79a10661f86eb3']
DEBUG:hw_diag.utilities.backup.myst:myst keystore files: ['/var/myst/keystore/UTC--2023-05-17T07-02-11.762878233Z--4e789ceca3f786a2ad8155144d79a10661f86eb3']
2023-05-30 00:08:38,153 - [DEBUG] - hw_diag.utilities.crypto - (crypto.py).calculate_file_hash -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/crypto.py:(19) - hash for ['/var/myst/keystore/UTC--2023-05-17T07-02-11.762878233Z--4e789ceca3f786a2ad8155144d79a10661f86eb3'] is : af44ac1f77f3384adc8119d2fd7a2354bd85b7ce2ff189eb60c7ffd6472991e9
DEBUG:hw_diag.utilities.crypto:hash for ['/var/myst/keystore/UTC--2023-05-17T07-02-11.762878233Z--4e789ceca3f786a2ad8155144d79a10661f86eb3'] is : af44ac1f77f3384adc8119d2fd7a2354bd85b7ce2ff189eb60c7ffd6472991e9
ERROR:hw_diag.wsgi:Exception on / [GET]
Traceback (most recent call last):
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/auth.py", line 69, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/views/diagnostics.py", line 79, in get_diagnostics
    backup_pending_services = services_pending_backup()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/__init__.py", line 96, in services_pending_backup
    id_hashes = identity_hashes()
                ^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/__init__.py", line 127, in identity_hashes
    id_hashes.update(current_plugin.identity_hash())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/thingsix.py", line 30, in identity_hash
    with open(file, 'r') as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/thix/gateways.yaml'
INFO:root:Running periodic hardware diagnostics
```

This is due to the myst and thix files not existing on miners that do not have these containers and/or where they are not initialised.

**Comment by shawaj** [comment]
This is from a device on a non-commercial fleet
```
INFO:hw_diag.utilities.balena_supervisor:200
2023-05-30 01:19:25,686 - [INFO] - hw_diag.utilities.balena_supervisor - (balena_supervisor.py)._make_request -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/balena_supervisor.py:(34) - {"api_port":48484,"ip_address":"192.168.0.101","os_version":"balenaOS 2.113.18","mac_address":"F0:4C:D5:58:EE:45 88:94:7E:AA:66:97","supervisor_version":"14.9.4","update_pending":false,"update_failed":false,"update_downloaded":false,"commit":"4fb0c5dc205ed43d9d8887c0b3c6c2e6","status":"Idle","download_progress":null}
INFO:hw_diag.utilities.balena_supervisor:{"api_port":48484,"ip_address":"192.168.0.101","os_version":"balenaOS 2.113.18","mac_address":"F0:4C:D5:58:EE:45 88:94:7E:AA:66:97","supervisor_version":"14.9.4","update_pending":false,"update_failed":false,"update_downloaded":false,"commit":"4fb0c5dc205ed43d9d8887c0b3c6c2e6","status":"Idle","download_progress":null}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): icanhazip.com:443
DEBUG:urllib3.connectionpool:https://icanhazip.com:443 "GET / HTTP/1.1" 200 15
2023-05-30 01:19:25,916 - [DEBUG] - hw_diag.utilities.backup.myst - (myst.py).identity_hash -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/myst.py:(28) - myst keystore files: []
DEBUG:hw_diag.utilities.backup.myst:myst keystore files: []
2023-05-30 01:19:25,917 - [DEBUG] - hw_diag.utilities.crypto - (crypto.py).calculate_file_hash -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/crypto.py:(19) - hash for [] is : e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG:hw_diag.utilities.crypto:hash for [] is : e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
ERROR:hw_diag.wsgi:Exception on / [GET]
Traceback (most recent call last):
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/auth.py", line 69, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/views/diagnostics.py", line 79, in get_diagnostics
    backup_pending_services = services_pending_backup()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/__init__.py", line 96, in services_pending_backup
    id_hashes = identity_hashes()
                ^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/__init__.py", line 127, in identity_hashes
    id_hashes.update(current_plugin.identity_hash())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/backup/thingsix.py", line 30, in identity_hash
    with open(file, 'r') as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/thix/gateways.yaml'
DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/store/ HTTP/1.1" 429 198
INFO:root:Running periodic hardware diagnostics
2023-05-30 01:19:26,696 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/lib/python3.11/site-packages/hm_pyhelper/miner_param.py:(38) - gateway_mfr response stdout: b'{\n  "key": "11mXsDPh3QQ9zifnHGqQkzbtEtxJ8xfbaVbZ88z2JBgqrLVLyzb",\n  "name": "modern-crimson-porcupine"\n}\n'
INFO:hm_pyhelper.miner_param:gateway_mfr response stdout: b'{\n  "key": "11mXsDPh3QQ9zifnHGqQkzbtEtxJ8xfbaVbZ88z2JBgqrLVLyzb",\n  "name": "modern-crimson-porcupine"\n}\n'
2023-05-30 01:19:26,698 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/lib/python3.11/site-packages/hm_pyhelper/miner_param.py:(39) - gateway_mfr response stderr: b''
INFO:hm_pyhelper.miner_param:gateway_mfr response stderr: b''
2023-05-30 01:19:26,700 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/hardware.py:(91) - Retrieving list of BLE device(s)
INFO:hw_diag.utilities.hardware:Retrieving list of BLE device(s)
2023-05-30 01:19:26,720 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/hardware.py:(114) - Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-58EE45.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
INFO:hw_diag.utilities.hardware:Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-58EE45.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
2023-05-30 01:19:26,721 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/hardware.py:(160) - Retrieving list of LTE device(s)
INFO:hw_diag.utilities.hardware:Retrieving list of LTE device(s)
2023-05-30 01:19:26,736 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/lib/python3.11/site-packages/hw_diag/utilities/hardware.py:(187) - Found the following LTE Devices: []
INFO:hw_diag.utilities.hardware:Found the following LTE Devices: []
INFO:root:Diagnostics shipping not requested, skipping.
INFO:root:Diagnostics complete
DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/envelope/ HTTP/1.1" 200 2
```
