### ISSUE TITLE
Latest miner bump broken diagnostics

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#75]
See below:

```
 diagnostics  Diagnostics loop started...
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/main.py", line 404, in <module>
 diagnostics      main()
 diagnostics    File "/opt/main.py", line 267, in main
 diagnostics      diagnostics["OK"] = str(pk_file[3])
 diagnostics  IndexError: list index out of range
```

Looks like this changes is the issue?
https://github.com/NebraLtd/hm-miner/commit/6f5f5cb4a9bd29ce3d1ef69f151f64471f084f16#diff-0e6697c77412680c0ae2160d7471440fc3df43cf171143ed589bdb8a8f4abd99R9

**Comment by shawaj** [comment]
Fixed by https://github.com/NebraLtd/helium-miner-software/pull/89
